Style/StringLiterals:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IndentationConsistency:
  Enabled: false
Style/Tab:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyLineBetweenDefs:
  Enabled: false