language:
  - ruby
rvm:
  - 2.3.3
sudo: false
notifications:
  slack: story-time:8J2jQOxFW4EM31eLhf6BYmaP
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
services:
  - postgresql
env:
  global:
    - RAILS_ENV=test
    - CXX=g++-4.9
before_install:
  - mkdir $PWD/travis-phantomjs
  - curl -sSL https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2 -o $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
install:
  - bundle install
  - chromedriver-update
  - nvm install stable && nvm alias default stable
  - npm install npm@latest -g
  - npm install -g yarn
  - npm --version
  - yarn install
  - rake db:setup

# Tip: No need to run xvfb if running headless testing. However, we're going to start with
# Poltergeist and switch to selenium if a test fails.
before_script:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - psql -c 'create database birdup_test;' -U postgres

script:
  - bundle exec rake db:schema:load
  - bundle exec rake